### ISSUE TITLE
Ruby / Vagrant winrm-elevated loaderror

### ISSUE THREAD

**Issue by xelerated** [Orange-Cyberdefense/GOAD#167]
This is a fresh install of Kali. getting the following when running install (check works without error)

[✓] launch vagrant
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require': cannot load such file -- winrm-elevated (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/communicators/winrm/shell.rb:12:in `<top (required)>'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/communicators/winrm/communicator.rb:6:in `require_relative'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/communicators/winrm/communicator.rb:6:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/communicators/winrm/plugin.rb:15:in `block in <class:Plugin>'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/registry.rb:27:in `get'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/machine.rb:269:in `communicate'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/machine.rb:151:in `initialize'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/vagrantfile.rb:83:in `new'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/vagrantfile.rb:83:in `machine'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/environment.rb:740:in `machine'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/v2/command.rb:186:in `each'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/plugins/commands/up/command.rb:87:in `execute'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/cli.rb:67:in `execute'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/lib/vagrant/environment.rb:301:in `cli'
        from /usr/share/rubygems-integration/all/gems/vagrant-2.3.4/bin/vagrant:243:in `<top (required)>'
        from /usr/bin/vagrant:25:in `load'
        from /usr/bin/vagrant:25:in `<main>'
/home/*/GOAD
[!] vagrant finish with error abort

**Comment by xelerated** [comment]
this worked: vagrant plugin install winrm-elevated
