### ISSUE TITLE
Unhandled exception while executing module on ad-relations.yml

### ISSUE THREAD

**Issue by Jugulaire** [Orange-Cyberdefense/GOAD#34]
I try to deploy the GOAD v2 on my labs to learn active directory. 
I have followed religiously the step for getting requierements:

 ```
sudo apt install python3.8-venv
cd ansible
virtualenv .venv
source .venv/bin/activate
python3 -m pip install --upgrade pip
python3 -m pip install ansible-core==2.12.6
python3 -m pip install pywinrm
ansible-galaxy install -r requirements.yml
ansible-playbook main.yml
```

But here is my output : 

```

PLAY [Read data files] ***********************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
ok: [192.168.56.12]
ok: [192.168.56.11]
ok: [192.168.56.10]
ok: [192.168.56.22]

TASK [save the Json data to a Variable as a Fact] ********************************************************************************************************************************************************
ok: [192.168.56.10]
ok: [192.168.56.11]
ok: [192.168.56.22]
ok: [192.168.56.12]

PLAY [Adjust rights configuration] ***********************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
ok: [192.168.56.12]
ok: [192.168.56.22]
ok: [192.168.56.10]
ok: [192.168.56.11]

TASK [settings/adjust_rights : Add domain users to local groups] *****************************************************************************************************************************************
changed: [192.168.56.12] => (item={'key': 'Administrators', 'value': ['essos\\daenerys.targaryen']})
changed: [192.168.56.22] => (item={'key': 'Administrators', 'value': ['north\\jeor.mormont']})
changed: [192.168.56.10] => (item={'key': 'Administrators', 'value': ['sevenkingdoms\\robert.baratheon', 'sevenkingdoms\\cersei.lannister']})
changed: [192.168.56.11] => (item={'key': 'Administrators', 'value': ['north\\eddard.stark', 'north\\catelyn.stark', 'north\\robb.stark']})
changed: [192.168.56.12] => (item={'key': 'Remote Desktop Users', 'value': ['essos\\Targaryen']})
changed: [192.168.56.22] => (item={'key': 'Remote Desktop Users', 'value': ['north\\Night Watch', 'north\\Mormont', 'north\\Stark']})
changed: [192.168.56.10] => (item={'key': 'Remote Desktop Users', 'value': ['sevenkingdoms\\Small Council']})
changed: [192.168.56.11] => (item={'key': 'Remote Desktop Users', 'value': ['north\\Stark']})

PLAY [cross domain groups] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************
ok: [192.168.56.12]
ok: [192.168.56.10]
ok: [192.168.56.11]

TASK [groups_domains : Reboot and wait for the AD system to restart] *************************************************************************************************************************************
changed: [192.168.56.10]
changed: [192.168.56.12]
changed: [192.168.56.11]

TASK [groups_domains : Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}}] *********************************************************************
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (3 retries left).
FAILED - RETRYING: [192.168.56.11]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (3 retries left).
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (2 retries left).
FAILED - RETRYING: [192.168.56.11]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (2 retries left).
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (1 retries left).
FAILED - RETRYING: [192.168.56.11]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (1 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
failed: [192.168.56.12] (item={'key': 'DragonsFriends', 'value': ['north.sevenkingdoms.local\\jon.snow', 'sevenkingdoms.local\\tyron.lannister', 'essos.local\\daenerys.targaryen']}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"key": "DragonsFriends", "value": ["north.sevenkingdoms.local\\jon.snow", "sevenkingdoms.local\\tyron.lannister", "essos.local\\daenerys.targaryen"]}, "msg": "Unhandled exception while executing module: Either the target name is incorrect or the server has rejected the client credentials."}
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (3 retries left).
failed: [192.168.56.11] (item={'key': 'AcrossTheSea', 'value': ['essos.local\\daenerys.targaryen']}) => {"added": [], "ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"key": "AcrossTheSea", "value": ["essos.local\\daenerys.targaryen"]}, "msg": "Could not find domain user, group, service account or computer named daenerys.targaryen", "removed": []}
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (2 retries left).
FAILED - RETRYING: [192.168.56.12]: Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}} (1 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
failed: [192.168.56.12] (item={'key': 'Spys', 'value': ['sevenkingdoms.local\\Small Council']}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"key": "Spys", "value": ["sevenkingdoms.local\\Small Council"]}, "msg": "Unhandled exception while executing module: Authentication failed on the remote side (the stream might still be available for additional authentication attempts)."}

```

The problem was already discussed on the issue #19 but since no information about the fix was given and reinstalling my venv + ansible didn't fix anything. I reopen another issue here because it must be different problem. 

I'm running Ubuntu 18.04 and the Vagrant part seem to be setup properly. 
Tried to launch the playbook 6 or 7 times but no luck for me.. 

Tried both the playbook alone and the main.yml 6 or 7 times. 

Any idea of whats wrong ? 

I have found the following comment in the playbook where the error occur : 

```
# doesen't work see : https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_domain_group_membership.ps1
# ligne 62 : use the given credentials to distant domain -> wrong
```

What is the fix i should implement if any ?

**Comment by EdgeW4lker** [comment]
Could you give us your system specs?

Have you tried a complete recreation of the VMs? (vagrant halt; vagrant destroy; reboot your system; restart all the setup process)

**Comment by Jugulaire** [comment]
Hey, i'm on Ubuntu 18.04. 
32gig of ram 1tb SSD. 

I have followed this script : 

```bash
#!/bin/bash
echo "Deploy GOAD v2 on Ubuntu 22.04"



# Add repositories
sudo add-apt-repository -y multiverse

# Get list of latest packages
sudo apt-get update

# Make sure we're running on latest versions of things installed
sudo apt-get -y autoupdate

# Check if we're running inside VirtualBox
if [ `dmidecode -s system-product-name` = "VirtualBox" ]; then
  # Install VirtualBox guest additions
  sudo apt-get install -y virtualbox-guest-utils virtualbox-guest-x11
fi

# Install base packages needed
sudo apt-get install -y git virtualbox python3-pip

# Download GOAD
cd /home/jugu/HDD
git clone https://github.com/Orange-Cyberdefense/GOAD goad

# Install specific version of Vagrant
wget https://releases.hashicorp.com/vagrant/2.2.18/vagrant_2.2.18_x86_64.deb
sudo dpkg --install vagrant_2.2.18_x86_64.deb

# Set up prerequisites, not doing a venv but could be changed to that
cd /home/jugu/HDD/goad/ansible
pip install --upgrade pip
pip install ansible-core==2.12.6
pip install pywinrm

# Install stuff needed for Ansible
ansible-galaxy install -r requirements.yml

# Install stuff needed for Vagrant
vagrant plugin install winrm
vagrant plugin install winrm-elevated

# Deploy VMs
cd /home/jugu/HDD/goad
vagrant up

if [ $? -ne 0 ]; then
  echo "Deployment failed"
  exit 1
fi

# Configure VMs
echo "Wait some minutes for VMs to settle, then configure them:"
echo .
echo "Run these commands:"
echo "# cd /opt/goad/ansible"
echo "# ansible-playbook main.yml"
```

Then launched the main.yml : 

```bash
ansible-playbook main.yml 
```

Got this error : 

```bash
The full traceback is:
A call to SSPI failed, see inner exception.
At line:64 char:21
+ ... up_member = Get-ADObject -Filter "SamAccountName -eq '$member' -and $ ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SecurityError: (:) [Get-ADObject], AuthenticationException
    + FullyQualifiedErrorId : ActiveDirectoryCmdlet:System.Security.Authentication.AuthenticationException,Microsoft.ActiveDirectory.Management.Commands.GetADObject

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 64

System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ServiceModel.Security.SecurityNegotiationException: A call to SSPI failed, see inner exception. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> System.ComponentModel.Win32Exception: The target principal name is incorrect
   --- End of inner exception stack trace ---
   at System.Net.Security.NegoState.StartSendAuthResetSignal(LazyAsyncResult lazyResult, Byte[] message, Exception exception)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.NegotiateStream.AuthenticateAsClient(NetworkCredential credential, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgrade(Stream stream, SecurityMessageProperty& remoteSecurity)
   --- End of inner exception stack trace ---

Server stack trace: 
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgrade(Stream stream, SecurityMessageProperty& remoteSecurity)
   at System.ServiceModel.Channels.StreamSecurityUpgradeInitiatorBase.InitiateUpgrade(Stream stream)
   at System.ServiceModel.Channels.ConnectionUpgradeHelper.InitiateUpgrade(StreamUpgradeInitiator upgradeInitiator, IConnection& connection, ClientFramingDecoder decoder, IDefaultCommunicationTimeouts defaultTimeouts, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.SendPreamble(IConnection connection, ArraySegment`1 preamble, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.DuplexConnectionPoolHelper.AcceptPooledConnection(IConnection connection, TimeoutHelper& timeoutHelper)
   at System.ServiceModel.Channels.ConnectionPoolHelper.EstablishConnection(TimeSpan timeout)
   at System.ServiceModel.Channels.ClientFramingDuplexSessionChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.OnOpen(TimeSpan timeout)
   at System.ServiceModel.Channels.CommunicationObject.Open(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOpenOnce.System.ServiceModel.Channels.ServiceChannel.ICallOnce.Call(ServiceChannel channel, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.CallOnceManager.CallOnce(TimeSpan timeout, CallOnceManager cascade)
   at System.ServiceModel.Channels.ServiceChannel.EnsureOpened(TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.ActiveDirectory.WebServices.Proxy.Resource.Get(Message request)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
   --- End of inner exception stack trace ---
   at Microsoft.ActiveDirectory.Management.AdwsConnection.ThrowAuthenticationRelatedExceptionIfAny(CommunicationException exception)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.SearchAnObject(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.AdwsConnection.Search(ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADWebServiceStoreAccess.Microsoft.ActiveDirectory.Management.IADSyncOperations.Search(ADSessionHandle handle, ADSearchRequest request)
   at Microsoft.ActiveDirectory.Management.ADObjectSearcher.GetRootDSE()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.GetRootDSE()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.GetConnectedStore()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.GetCmdletSessionInfo()
   at Microsoft.ActiveDirectory.Management.Commands.ADGetCmdletBase`3.ADGetCmdletBaseBeginCSRoutine()
   at Microsoft.ActiveDirectory.Management.CmdletSubroutinePipeline.Invoke()
   at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
failed: [192.168.56.11] (item={'key': 'AcrossTheSea', 'value': ['essos.local\\daenerys.targaryen']}) => {
    "ansible_loop_var": "item",
    "attempts": 3,
    "changed": false,
    "item": {
        "key": "AcrossTheSea",
        "value": [
            "essos.local\\daenerys.targaryen"
        ]
    },
    "msg": "Unhandled exception while executing module: A call to SSPI failed, see inner exception."
}

```

Note : i have tried to relaunch everything 6 times. 
How can i get the powershell command executed to debug/do it manually ? 

Thanks

**Comment by Jugulaire** [comment]
Hi, after some debugging, I finally figured out. 
My Windows machine where just rebooting and making some update. 

I did use the exact same script I linked, redone everything and get the same error. 
Waited something like 25 minutes and everything worked after it. 

Just let Windows do its shitty update.
