### ISSUE TITLE
Issue with multi-domain forest to a domain group

### ISSUE THREAD

**Issue by HanzCoder** [Orange-Cyberdefense/GOAD#40]
Having issues with this specific Ansible Task- 

- name: "Add a domain user/group from another Domain in the multi-domain forest to a domain group : {{domain_server}}"
  community.windows.win_domain_group_membership:
    # domain_server: "{{domain_server}}"
    domain_username: "{{domain_username}}"
    domain_password: "{{domain_password}}"
    name: "{{item.key}}"
    members: "{{ item.value }}"
    state: Present
  with_dict: "{{ domain_groups_members }}"
  register: group_membership
  until: "group_membership is not failed"
  retries: 3
  delay: 120
  
  
Ansible Output of the error
![image](https://user-images.githubusercontent.com/3400048/190536311-175db4d8-6be1-43bd-b7af-3974fd964aed.png)

'''An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
failed: [192.168.56.11] (item={'key': 'AcrossTheSea', 'value': ['essos.local\\daenerys.targaryen']}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"key": "AcrossTheSea", "value": ["essos.local\\daenerys.targaryen"]}, "msg": "Unhandled exception while executing module: The server has rejected the client credentials."}

An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
failed: [192.168.56.12] (item={'key': 'DragonsFriends', 'value': ['north.sevenkingdoms.local\\jon.snow', 'sevenkingdoms.local\\tyron.lannister', 'essos.local\\daenerys.targaryen']}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"key": "DragonsFriends", "value": ["north.sevenkingdoms.local\\jon.snow", "sevenkingdoms.local\\tyron.lannister", "essos.local\\daenerys.targaryen"]}, "msg": "Unhandled exception while executing module: The server has rejected the client credentials."}'

An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at Microsoft.ActiveDirectory.Management.Commands.ADCmdletBase`1.BeginProcessing()
failed: [192.168.56.12] (item={'key': 'Spys', 'value': ['sevenkingdoms.local\\Small Council']}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"key": "Spys", "value": ["sevenkingdoms.local\\Small Council"]}, "msg": "Unhandled exception while executing module: Either the target name is incorrect or the server has rejected the client credentials."}
''
Some troubleshooting : 
Domain Trust Verification And ADUC error showing issue Adding "Small Council@sevenkingdoms.local" to "spys@essos.local" Similar issue with the other Security groups tagged with "multi domain"  
![image](https://user-images.githubusercontent.com/3400048/190537250-e474d9b7-d1f1-4506-b0ad-df92a0689894.png)

nslookup to sevenkingdoms.local  from essos.local (dc03 192.168.56.12)
![image](https://user-images.githubusercontent.com/3400048/190537769-75d96c63-6523-4794-a0f3-d78180e852b8.png)

nslookup to essos.local from sevenkingdoms.local (dc01 192.168.56.10)
![image](https://user-images.githubusercontent.com/3400048/190538152-cfe5ee85-afeb-452f-8453-6726edf93108.png)

**Comment by HanzCoder** [comment]
Closing issue - Fixed the Trust & DNS issue manually
